### ISSUE TITLE
[13.0] [base_accounting_kit] Unable to select Vendor in Asset form

### ISSUE THREAD

**Issue by micksatana** [CybroOdoo/CybroAddons#137]
**Steps to reproduct**

1)  Fresh install Odoo 13
2) Install Odoo 13 Full Accounting Kit (base_accounting_kit)
3) Go to Accounting > Management > Assets
4) Click Create button
5) Select Vendor

**Expected behaviour**

Able to select vendor

**Current behaviour**

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1701, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_partner.py", line 756, in _name_search
    return super(Partner, self)._name_search(name, args, operator=operator, limit=limit, name_get_uid=name_get_uid)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1714, in _name_search
    ids = self._search(args, limit=limit, access_rights_uid=access_rights_uid)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_partner.py", line 691, in _search
    count=count, access_rights_uid=access_rights_uid)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4363, in _search
    query = self._where_calc(args)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4101, in _where_calc
    e = expression.expression(domain, self)
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 674, in __init__
    self.parse()
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 855, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'supplier' in leaf "<osv.ExtendedLeaf: ('supplier', '=', True) on res_partner (ctx: )>"
```

**Workaround**

1) Turn-on debug mode
2) Edit the view
3) Remove domain attribute

Change from...

```
<field name="partner_id" string="Vendor" domain="[('supplier', '=', True)]"/>
```

to

```
<field name="partner_id" string="Vendor"/>
```

**Comment by CybroOdoo** [comment]
HI,
This issue is already fixed. you have to get the updated module.

Thanks
