### ISSUE TITLE
Error while installing. "Element '<field name="journal_ids">' cannot be located in parent view

### ISSUE THREAD

**Issue by Aadeelyoo** [CybroOdoo/CybroAddons#152]
I have uninstalled om_accounting trying this module. But when i am trying to install i am having error below.
I have restarted service
I have upgraded base
I have upgraded all the dependencies.
But still facing same error while install.

Fresh new version of odoo 13 ce and base_accounting downloaded.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 664, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: Element '<field name="journal_ids">' cannot be located in parent view

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 712, in parse
    self._tag_root(de)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 674, in _tag_root
    f(rec)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 4084, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3998, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3779, in create
    fields[0].determine_inverse(batch_recs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3568, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 1176, in _validate_fields
    check(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 387, in _check_xml
    view_def = view.read_combined(['arch'])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 738, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 687, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 666, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Element '<field name="journal_ids">' cannot be located in parent view

Error context:
View `Tax Reports`
[view_id: 1505, xml_id: n/a, model: account.tax.report, parent_id: 828]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 721, in parse
    exc_info[2]
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 712, in parse
    self._tag_root(de)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 674, in _tag_root
    f(rec)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 4084, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3998, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3779, in create
    fields[0].determine_inverse(batch_recs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3568, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 1176, in _validate_fields
    check(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 387, in _check_xml
    view_def = view.read_combined(['arch'])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 738, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 687, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 666, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
odoo.tools.convert.ParseError: "Element '<field name="journal_ids">' cannot be located in parent view

Error context:
View `Tax Reports`
[view_id: 1505, xml_id: n/a, model: account.tax.report, parent_id: 828]" while parsing file:/d:/odoo%20development/readymade/base_accounting_kit/wizard/tax_report.xml:2, near
<odoo>

    <record id="accounting_tax_report_view" model="ir.ui.view">
        <field name="name">Tax Reports</field>
        <field name="model">account.tax.report</field>
        <field name="inherit_id" ref="account.account_common_report_view"/>
        <field name="arch" type="xml">
            <data>
                <field name="journal_ids" position="replace"/>
                <field name="target_move" position="replace"/>
                <xpath expr="//field[@name='date_from']" position="attributes">

                </xpath>
                <xpath expr="//field[@name='date_to']" position="attributes">
                </xpath>
            </data>
        </field>
    </record>

    <record id="action_account_tax_report" model="ir.actions.act_window">
        <field name="name">Tax Reports</field>
        <field name="res_model">account.tax.report</field>
        <field name="type">ir.actions.act_window</field>
        <field name="view_mode">form</field>
        <field name="view_id" ref="accounting_tax_report_view"/>
        <field name="context">{}</field>
        <field name="target">new</field>
    </record>

    <menuitem id="menu_tax_report" name="Tax Report" sequence="8" action="action_account_tax_report" parent="base_accounting_kit.account_reports_audit" groups="account.group_account_manager,account.group_account_user"/>

</odoo>

**Comment by CybroOdoo** [comment]
Hi
The issue is because you are using other custom modules.
