### ISSUE TITLE
Two Issues in Product_Return_POS in Odoo 13 CE

### ISSUE THREAD

**Issue by wshamasneh** [CybroOdoo/CybroAddons#159]
I found two issues in product_return_pos under Odoo 13 CE:

1.  Whenever use the find option to search for specific receipt, then the Return button is no longer operate and nothing else is happening. Although once all of the orders are populated and you found the order using the scroll option, the Return button works and new screen show up for returning the items.
2.  If the return is completed based on the issue mentioned up in 1 and before complete the refund, system allows me to add (exchange) the product with new different one (this option is so great if could be completed) but once select the payment, update the amount and Validate the receipt then an error is show up and preventing me from completing the process until remove the added product then the refund can be completed. The error is:   Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1327, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\point_of_sale\models\pos_order.py", line 443, in create_from_ui
    order_ids.append(self._process_order(order, draft, existing_order))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\point_of_sale\models\pos_order.py", line 120, in _process_order
    pos_order = self.create(self._order_fields(order))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\pos_kitchen_printer\models\pos_order.py", line 14, in _order_fields
    order_fields = super(PosOrder, self)._order_fields(ui_order)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\product_return_pos\models\pos_return.py", line 67, in _order_fields
    ('id', '=', uptd[2]['line_id'])], limit=1)
KeyError: 'line_id'

Thank you so much for your continuing support and for developing great features.

**Comment by YohanAvishke** [comment]
You can hot fix issue 2 by adding conditions,
```py
 if uptd[2] and hasattr(uptd[2], 'line_id'):
```
Code will look like,
```py
 for uptd in updated_lines:
   if uptd[2] and hasattr(uptd[2], 'line_id'):
      line = self.env['pos.order.line'].search(
          [('order_id', '=', parent_order.id), ('id', '=', uptd[2]['line_id'])],
          limit=1)
      if line:
          line.returned_qty += -(uptd[2]['qty'])
```
But obviously this doesn't fix the issue, it just makes it not appear
