### ISSUE TITLE
[15] Install errors and dashboard errors

### ISSUE THREAD

**Issue by danielosser** [CybroOdoo/CybroAddons#182]
Just installed on Odoo 15 Community (pristine) and there are several errors. 

Log WARNINGs during install:
```
2021-10-10 18:23:05,992 158054 WARNING test15accountkit odoo.fields: Field budget.budget.state: unknown parameter 'track_visibility', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
```

```
2021-10-10 18:23:06,634 158054 WARNING test15accountkit odoo.addons.base.models.ir_ui_view: <img> tag must contain an alt attribute
View error context:
{'file': '/opt/odoo/shared/odoo15/community/base_account_budget/views/account_budget_views.xml',
 'line': 31,
 'name': 'budget.kanban',
 'view': ir.ui.view(739,),
 'view.model': 'budget.budget',
 'view.parent': ir.ui.view(),
 'xmlid': 'view_budget_kanban'} 
```

```
2021-10-10 18:23:13,911 158054 WARNING test15accountkit odoo.models: The model multiple.invoice has no _description 
2021-10-10 18:23:13,912 158054 WARNING test15accountkit odoo.models: The model report.base_accounting_kit.report_multiple_invoice has no _description 
```

This produces an error:
```
2021-10-10 18:23:15,463 158054 WARNING test15accountkit py.warnings: /opt/odoo/odoo15/odoo/fields.py:722: UserWarning: Field account.financial.report.level should be declared with recursive=True
  File "/usr/lib64/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
...
  File "/opt/odoo/odoo15/odoo/fields.py", line 722, in resolve_depends
    warnings.warn(f"Field {self} should be declared with recursive=True")
```

**Comment by xendarboh** [comment]
saw similar warnings, then:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 583, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4399, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4328, in _load_records_create
    return self.create(values)
  File "<decorator-gen-184>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_payment_method.py", line 28, in create
    if information.get('mode') == 'multi':
AttributeError: 'NoneType' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1336, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1324, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 483, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 600, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 693, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /mnt/common-addons/cybrosys/base_accounting_kit/data/account_pdc_data.xml:5, somewhere inside
<record id="account_payment_method_pdc_in" model="account.payment.method">
            <field name="name">PDC</field>
            <field name="code">pdc</field>
            <field name="payment_type">inbound</field>
        </record>
```

**Comment by xendarboh** [comment]
working now so far
