### ISSUE TITLE
Error: QWeb2: Template 'CRMdashboard' not found

### ISSUE THREAD

**Issue by thiagoblisboa** [CybroOdoo/CybroAddons#184]
I've installed the kit crm odoo 14 on my odoo and there is the error below:

Erro:

Traceback:
Error: QWeb2: Template 'CRMdashboard' not found
    at Object.exception (https://gestao.mtclean.com.br/web/content/1059-c529333/web.assets_common.js:4385:7)
    at Engine._render (https://gestao.mtclean.com.br/web/content/1059-c529333/web.assets_common.js:4430:103)
    at Engine.render (https://gestao.mtclean.com.br/web/content/1059-c529333/web.assets_common.js:4426:151)
    at Class.renderElement (https://gestao.mtclean.com.br/web/content/1369-d904dd3/web.assets_backend.js:480:452)
    at Class.prototype.<computed> [as renderElement] (https://gestao.mtclean.com.br/web/content/1059-c529333/web.assets_common.js:4620:488)
    at Class.renderElement (https://gestao.mtclean.com.br/web/content/1369-d904dd3/web.assets_backend.js:9089:9156)
    at Class.prototype.<computed> [as renderElement] (https://gestao.mtclean.com.br/web/content/1059-c529333/web.assets_common.js:4620:488)
    at https://gestao.mtclean.com.br/web/content/1059-c529333/web.assets_common.js:4948:6 

How could I solve this issue?

**Comment by lauraruggerilinea** [comment]
I've the some problem.

Error:
`Error: QWeb2: Template 'CRMdashboard' not found
    at Object.exception (.../web/content/620-028307d/web.assets_common.js:4410:7)
    at Engine._render (.../web/content/620-028307d/web.assets_common.js:4455:103)
    at Engine.render (.../web/content/620-028307d/web.assets_common.js:4451:151)
    at Class.renderElement .../web/content/1000-89228cb/web.assets_backend.js:487:452)
    at Class.prototype.<computed> [as renderElement] (.../web/content/620-028307d/web.assets_common.js:4648:488)
    at Class.renderElement (..../web/content/1000-89228cb/web.assets_backend.js:6637:9156)
    at Class.prototype.<computed> [as renderElement] (.../web/content/620-028307d/web.assets_common.js:4648:488)
    at .../web/content/620-028307d/web.assets_common.js:4990:6`

**Comment by t0p4n5** [comment]
I have also a problem
Traceback:
Error: QWeb2: Template 'CRMdashboard' not found
    at Object.exception (http://localhost:8069/web/content/854-2dde53e/web.assets_common.js:4408:7)
    at Engine._render (http://localhost:8069/web/content/854-2dde53e/web.assets_common.js:4453:103)
    at Engine.render (http://localhost:8069/web/content/854-2dde53e/web.assets_common.js:4449:151)
    at Class.renderElement (http://localhost:8069/web/content/908-b6afeb6/web.assets_backend.js:488:452)
    at prototype.<computed> [as renderElement] (http://localhost:8069/web/content/854-2dde53e/web.assets_common.js:4651:488)
    at Class.renderElement (http://localhost:8069/web/content/908-b6afeb6/web.assets_backend.js:6664:9156)
    at prototype.<computed> [as renderElement] (http://localhost:8069/web/content/854-2dde53e/web.assets_common.js:4651:488)
    at http://localhost:8069/web/content/854-2dde53e/web.assets_common.js:4996:6

please help
