### ISSUE TITLE
Dashboard error

### ISSUE THREAD

**Issue by rr10** [CybroOdoo/CybroAddons#189]
UncaughtPromiseError > KeyNotFoundError
Uncaught Promise > Cannot find crm_dashboard in this registry!
KeyNotFoundError: Cannot find crm_dashboard in this registry!
    at Registry.get (https://e.cloud/web/assets/740-d8d7572/web.assets_backend.min.js:929:76)
    at _executeClientAction (https://e.cloud/web/assets/740-d8d7572/web.assets_backend.min.js:2276:87)
    at Object.doAction (https://1e.cloud/web/assets/740-d8d7572/web.assets_backend.min.js:2293:192)
    at async Object.selectMenu (https://ne.cloud/web/assets/740-d8d7572/web.assets_backend.min.js:2395:1)

**Comment by wasdik** [comment]
Odoo 15. crm_dashboard. When I click on the CRM menu item, I get an error:
UncaughtPromiseError > KeyNotFoundError
Uncaught Promise > Cannot find crm_dashboard in this registry!
KeyNotFoundError: Cannot find crm_dashboard in this registry!
    at Registry.get (https://sitename.com/web/assets/1030-340270f/web.assets_backend.min.js:936:76)
    at _executeClientAction (https://sitename.com/web/assets/1030-340270f/web.assets_backend.min.js:2284:87)
    at Object.doAction (https://sitename.com/web/assets/1030-340270f/web.assets_backend.min.js:2301:192)
    at async WebClient.loadRouterState (https://sitename.com/web/assets/1030-340270f/web.assets_backend.min.js:2457:268)

**Comment by wasdik** [comment]
> UncaughtPromiseError > KeyNotFoundError Uncaught Promise > Cannot find crm_dashboard in this registry! KeyNotFoundError: Cannot find crm_dashboard in this registry! at Registry.get (https://e.cloud/web/assets/740-d8d7572/web.assets_backend.min.js:929:76) at _executeClientAction (https://e.cloud/web/assets/740-d8d7572/web.assets_backend.min.js:2276:87) at Object.doAction (https://1e.cloud/web/assets/740-d8d7572/web.assets_backend.min.js:2293:192) at async Object.selectMenu (https://ne.cloud/web/assets/740-d8d7572/web.assets_backend.min.js:2395:1)

Did you find a solution to this problem?
