### ISSUE TITLE
[15.0] installation error: company_id must be present in view but is missing at CybroAddons/base_accounting_kit/wizard/aged_partner.xml

### ISSUE THREAD

**Issue by MosabWadea** [CybroOdoo/CybroAddons#194]
whenever I try to install base_accounting_kit in odoo 15.0 I am getting this error:

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/odoo/odoo/odoo/tools/convert.py", line 583, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo/odoo/models.py", line 4418, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo/odoo/models.py", line 4339, in _load_records_create
    return self.create(values)
  File "<decorator-gen-42>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 539, in create
    result = super(View, self.with_context(ir_ui_view_partial_validation=True)).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/odoo/models.py", line 4071, in create
    records = self._create(data_list)
  File "/odoo/odoo/odoo/models.py", line 4236, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/odoo/odoo/odoo/models.py", line 1367, in _validate_fields
    check(self)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 460, in _check_xml
    raise err.with_traceback(e.__traceback__) from None
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 434, in _check_xml
    view._validate_view(combined_arch, view.model)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 1300, in _validate_view
    name_manager.check(self)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 2267, in check
    view._raise_view_error(msg)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 739, in _raise_view_error
    raise err from from_exception
odoo.exceptions.ValidationError: Error while validating view near:

<form string="Report Options" __validate__="1">
                <group col="4">
                    <field name="date_from"/>

Field 'company_id' used in domain of field 'journal_ids' ([('company_id', '=', company_id)]) must be present in view but is missing.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo/addons/web/controllers/main.py", line 1352, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo/addons/web/controllers/main.py", line 1340, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/odoo/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo/odoo/addons/base/models/ir_module.py", line 483, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo/odoo/addons/base/models/ir_module.py", line 600, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/odoo/odoo/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/odoo/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/odoo/odoo/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odoo/odoo/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/odoo/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/odoo/odoo/odoo/tools/convert.py", line 691, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /odoo/custom/CybroAddons/base_accounting_kit/wizard/aged_partner.xml:4
Error while validating view near:

<form string="Report Options" __validate__="1">
                <group col="4">
                    <field name="date_from"/>

Field 'company_id' used in domain of field 'journal_ids' ([('company_id', '=', company_id)]) must be present in view but is missing.

View error context:
{'file': '/odoo/custom/CybroAddons/base_accounting_kit/wizard/aged_partner.xml',
 'line': 1,
 'name': 'Aged Partner Balance',
 'view': ir.ui.view(895,),
 'view.model': 'account.aged.trial.balance',
 'view.parent': ir.ui.view(),
 'xmlid': 'account_aged_balance_view'}
```

**Comment by MosabWadea** [comment]
I am going to fix this issue by adding the field company_id as invisible in the file.

**Comment by MosabWadea** [comment]
I have created [pr#195](https://github.com/CybroOdoo/CybroAddons/pull/195) to fix this issue. this fix has worked for me
Please approve the pr

Thanks
