### ISSUE TITLE
[15.0] product_visibility_website; corrupts res.config.settings

### ISSUE THREAD

**Issue by mads-vkd** [CybroOdoo/CybroAddons#202]
After installing the module it's no longer possible to access Settings:

ids = OrderedSet(browse(it).id for it in command[2])
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[...]odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "[...]odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: 'bool' object is not iterable

**Comment by gezzzan** [comment]
had the same issue, I think the app should initialize ir_config_parameter defaults
i solved it in db
`INSERT INTO ir_config_parameter (key, value) VALUES ('filter_mode', 'product_only');
INSERT INTO ir_config_parameter (key, value) VALUES ('product_visibility_guest_user', 'False');
INSERT INTO ir_config_parameter (key, value) VALUES ('website_product_visibility.available_product_ids', '[]');
INSERT INTO ir_config_parameter (key, value) VALUES ('website_product_visibility.available_cat_ids', '[]');`
