### ISSUE TITLE
Error while creating invoice from sale order

### ISSUE THREAD

**Issue by rdcprojects** [CybroOdoo/CybroAddons#21]
I am getting below error while creating an invoice from sale order:

```
Traceback (most recent call last):
  File "F:\Projects\odoo-10.0\odoo\http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "F:\Projects\odoo-10.0\odoo\http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "F:\Projects\odoo-10.0\odoo\http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "F:\Projects\odoo-10.0\odoo\service\model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "F:\Projects\odoo-10.0\odoo\http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "F:\Projects\odoo-10.0\odoo\http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "F:\Projects\odoo-10.0\odoo\http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "F:\Projects\odoo-10.0\addons\web\controllers\main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "F:\Projects\odoo-10.0\addons\web\controllers\main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "F:\Projects\odoo-10.0\odoo\api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "F:\Projects\odoo-10.0\odoo\api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "F:\Projects\odoo-10.0\addons\sale\wizard\sale_make_invoice_advance.py", line 128, in create_invoices
    sale_orders.action_invoice_create()
  File "F:\Projects\odoo-10.0\addons\sale\models\sale.py", line 376, in action_invoice_create
    invoice.compute_taxes()
  File "F:\Projects\odoo-10.0\addons\account\models\account_invoice.py", line 436, in compute_taxes
    tax_grouped = invoice.get_taxes_values()
  File "F:\Projects\odoo-10.0\addons\account\models\account_invoice.py", line 639, in get_taxes_values
    val = self._prepare_tax_line_vals(line, tax)
  File "F:\Projects\odoo-10.0\addons\account\models\account_invoice.py", line 616, in _prepare_tax_line_vals
    'base': tax['base'],
KeyError: 'base'
```

I do not have any third party addons enabled.

**Comment by CybroOdoo** [comment]
Hello, this was caused by an Odoo updation. We updated our module too. Hope you won't get the module again
