### ISSUE TITLE
[16][whatsapp_mail_messaging][BUG] after installing the module Odoo backend not loading/Error: QWeb2: Template 'whatsapp_mail_messaging.whatsapp_icon' not found

### ISSUE THREAD

**Issue by tiagoclementemorgado** [CybroOdoo/CybroAddons#227]
After installing the module in Odoo 16 community Odoo backend not working anymore and following errors are shown in the browser console.

web.assets_backend.min.js:652 OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:1212:101)
    at owl.App.handleError (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:2039:29)
    at ComponentNode.initiateRender (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:1520:19)

**Caused by: Error: QWeb2: Template 'global_mail_message.mail_icon' not found**
    at Object.exception (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:5474:7)
    at Engine._render (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:5518:103)
    at Engine.render (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:5514:151)
    at Class.renderElement (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:6022:775)
    at http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:6032:6
    at async Promise.all (index 0)
    at async ComponentNode.initiateRender (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:1519:36)
handleError @ web.assets_backend.min.js:652
web.assets_backend.min.js:652 OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:1212:101)
    at owl.App.handleError (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:2039:29)
    at ComponentNode.initiateRender (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:1520:19)

**Caused by: Error: QWeb2: Template 'whatsapp_mail_messaging.whatsapp_icon' not found**
    at Object.exception (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:5474:7)
    at Engine._render (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:5518:103)
    at Engine.render (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:5514:151)
    at Class.renderElement (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:6022:775)
    at http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:6032:6
    at async Promise.all (index 0)
    at async ComponentNode.initiateRender (http://localhost:8016/web/assets/538-6df5640/web.assets_common.min.js:1519:36)

**Comment by CybroOdoo** [comment]
Hi @tiagoclementemorgado,

Thank you for reporting the issue. Please check the updated code
