### ISSUE TITLE
odoo_chatgpt_connector : AccessError on ir.config_parameter

### ISSUE THREAD

**Issue by myrrkel** [CybroOdoo/CybroAddons#235]
https://github.com/CybroOdoo/CybroAddons/blob/27868a4a59650b61a0dcec853123952bff2a1cfb/odoo_chatgpt_connector/static/src/js/submit_request.js#L30

This will raise an error if the user is not logged as administrator. But anyway, you should not get the api key on the client side, this is a security issue. You may create a controller that return the gpt3 answer to your function for example.

```
Server application error
 Error code: 200 
 Error message: Odoo Server Error 
 Error data message:
 You are not allowed to access 'System Parameter' (ir.config_parameter) records.

This operation is allowed for the following groups:
	- Administration/Settings

Contact your administrator to request access if necessary. 
 Error data debug:
 Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 457, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 430, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/ir_config_parameter.py", line 66, in get_param
    self.check_access_rights('read')
  File "/opt/odoo/odoo/models.py", line 3428, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "/opt/odoo/odoo/addons/base/models/ir_model.py", line 1895, in check
    raise AccessError(msg)
odoo.exceptions.AccessError: You are not allowed to access 'System Parameter' (ir.config_parameter) records.

This operation is allowed for the following groups:
	- Administration/Settings

Contact your administrator to request access if necessary.
```

**Comment by CybroOdoo** [comment]
Hi @myrrkel ,

Download the latest version of the module and try.
