### ISSUE TITLE
Error after installing hr_zk_attendance

### ISSUE THREAD

**Issue by carlos-lh** [CybroOdoo/CybroAddons#236]
i've installed ubuntu server 20.04 on a virtual machine, then installed odoo 16, activated the modules basic_setup, hr and hr_attendance. Upload your module to the custom_addons folder, activated developer mode, updated app list, instaled your module. Then i go to attendance, see the new menu (biometric manager), i can add the device and the connection work BUT here is the first issue:
when i try to download manually an error pops up saying that:

> A new attendance record cannot be created for _USER REGISTERED ONLY ON THE DEVICE_, his entry was already registered at 04/27/2022 08:18:12

So, from this error i can tell that the communication it's working but for some reason, doesn't download the data. i try this with other device (same model) but with no data, registered myself and did a check in check out, download the data, odoo created an employee with my data from the device and added the attendance. So i think the problem could be the amount of data or the amount of time between the oldest checkin and today.

The second problem is the attendance menu on the attendance module, before i install the module i can open this option, after i installed it i can't. This is the error message: 

 ```
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo-server/odoo/http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo-server/odoo/http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo-server/addons/web/controllers/action.py", line 34, in load
    action = request.env[action_type].sudo().browse([action_id]).read()
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions.py", line 272, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/opt/odoo/odoo-server/odoo/models.py", line 2994, in read
    return self._read_format(fnames=fields, load=load)
  File "/opt/odoo/odoo-server/odoo/models.py", line 3132, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/odoo/odoo-server/odoo/models.py", line 5851, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1188, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1347, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo-server/odoo/models.py", line 4196, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions.py", line 240, in _compute_search_view
    fvg = self.env[act.res_model].get_view(act.search_view_id.id, 'search')
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 2665, in get_view
    result = dict(self._get_view_cache(view_id, view_type, **options))
  File "<decorator-gen-48>", line 2, in _get_view_cache
  File "/opt/odoo/odoo-server/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 2625, in _get_view_cache
    arch, view = self._get_view(view_id, view_type, **options)
  File "/opt/odoo/odoo-server/addons/web/models/models.py", line 241, in _get_view
    arch, view = super()._get_view(view_id, view_type, **options)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 2572, in _get_view
    arch = view._get_combined_arch()
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 991, in _get_combined_arch
    arch = root.with_prefetch(tree_views._prefetch_ids)._combine(hierarchy)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 932, in _combine
    combined_arch = view.apply_inheritance_specs(combined_arch, arch)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 869, in apply_inheritance_specs
    self._raise_view_error(str(e), specs_tree)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 746, in _raise_view_error
    raise err from from_exception
ValueError: Element '<search string="Hr Attendance Search">' cannot be located in parent view

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://45.228.190.32:8069/web/assets/349-f368e85/web.assets_backend.min.js:968:163)
    at XMLHttpRequest.<anonymous> (http://45.228.190.32:8069/web/assets/349-f368e85/web.assets_backend.min.js:975:13)
```

**Comment by CybroOdoo** [comment]
HI @carlos-lh,
Please get the latest version of this module from app store and try.
