### ISSUE TITLE
Issue while using image_capture_upload_widget , error comes when module is uploaded on cloud (other then local) and when same camera icon is clicked it generated following error

### ISSUE THREAD

**Issue by hamzaazeempk** [CybroOdoo/CybroAddons#271]
![image](https://github.com/CybroOdoo/CybroAddons/assets/52909760/2c2db8b1-c81d-46dd-b70c-594f798012f0)
Issue while using image_capture_upload_widget , error comes when module is uploaded on cloud (other then local) and when same camera icon is clicked it generated following error
Firefox:
UncaughtPromiseError > TypeError

Uncaught Promise > navigator.mediaDevices is undefined

TypeError: navigator.mediaDevices is undefined
    OnClickOpenCamera@http://someip:8074/web/assets/634-f501f5d/web.assets_backend.min.js:17417:287
    mainEventHandler@http://someip:8074/web/assets/621-815d585/web.assets_common.min.js:2090:77
    listener@http://someip:8074/web/assets/621-815d585/web.assets_common.min.js:1287:15

 Chrome:
 UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'getUserMedia')

TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at ImageCapture.OnClickOpenCamera (http://someip:8074/web/assets/634-f501f5d/web.assets_backend.min.js:17417:316)
    at Object.mainEventHandler (http:/someip:8074/web/assets/621-815d585/web.assets_common.min.js:2090:77)
    at HTMLButtonElement.listener (http://someip:8074/web/assets/621-815d585/web.assets_common.min.js:1287:15)

**Comment by hamzaazeempk** [comment]
I was trying over http , it was allowed working fine our https. 
to test you can use  enable flag if you have http. 

chrome://flags/#unsafely-treat-insecure-origin-as-secure
add like this and it will work, Thanks
![image](https://github.com/CybroOdoo/CybroAddons/assets/52909760/7bc42b28-5910-40c2-9241-1eac369739f1)
