### ISSUE TITLE
[16 CE] Dynamic Financial Reports issue with other languages

### ISSUE THREAD

**Issue by LFPSGS** [CybroOdoo/CybroAddons#274]
Hi Team! Thanks for making these open source! It looks great!

However, when translating to Portuguese Brazilian, the Day Book, General Ledger, Cash Ledger and other reports stop working at all.

By simply clicking on "APPLY", odoo presents this message: 

UncaughtClientError > TypeError
Uncaught Javascript Error > Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
at Class.apply_filter ([https://](https://ODOO-URL/web/assets/308-099db8e/web.assets_backend.min.js:16524:66)odoo-URL[/web/assets/308-099db8e/web.assets_backend.min.js:16524:66)](https://ODOO-URL/web/assets/308-099db8e/web.assets_backend.min.js:16524:66) "‌")
at HTMLButtonElement.<anonymous> (https://ODOO-URL/web/assets/269-428e76a/web.assets_common.min.js:5885:11) "‌")
at HTMLDivElement.dispatch (https://ODOO-URL/web/assets/269-428e76a/web.assets_common.min.js:2448:447) "‌")
at elemData.handle (https://ODOO-URL/web/assets/269-428e76a/web.assets_common.min.js:2434:166) "‌")

Also, none of the JS words became translated inside the report (even tho I have them translated in a PO file)
[pt_BR.po.zip](https://github.com/CybroOdoo/CybroAddons/files/12408311/pt_BR.po.zip)

I'm attaching the PO file just in case.

Regards,
Luiz Fernando

Luiz Fernando

**Comment by GuilhermeKimoto** [comment]
has this problem been resolved?

**Comment by walid6677** [comment]
any one find solution for this problem

**Comment by LFPSGS** [comment]
Hi @walid6677 since they never responded, I stopped using this module and replace it with MIS BUILDER (which is an OCA report builder engine), but i had to build my reports from scratch.
