### ISSUE TITLE
[17.0] odoo_product_tags - product_tag_ids must have type 'boolean', 'integer', 'float', 'char', 'selection', 'many2one' or 'datetime'

### ISSUE THREAD

**Issue by coolbirdzik** [CybroOdoo/CybroAddons#319]
My Odoo version 17.0.post20240524
I think Odoo 17 not support product_tag_ids as Many2many in res.config.settings model

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/odoo/http.py", line 1770, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/local/lib/python3.10/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/local/lib/python3.10/dist-packages/odoo/http.py", line 1797, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/local/lib/python3.10/dist-packages/odoo/http.py", line 2001, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/local/lib/python3.10/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/local/lib/python3.10/dist-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/usr/local/lib/python3.10/dist-packages/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/local/lib/python3.10/dist-packages/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/odoo/addons/web/models/models.py", line 73, in web_save
    self = self.create(vals)
  File "<decorator-gen-103>", line 2, in create
  File "/usr/local/lib/python3.10/dist-packages/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/usr/local/lib/python3.10/dist-packages/odoo/addons/base/models/res_config.py", line 746, in create
    return super().create(vals_list)
  File "<decorator-gen-12>", line 2, in create
  File "/usr/local/lib/python3.10/dist-packages/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/usr/local/lib/python3.10/dist-packages/odoo/models.py", line 4546, in create
    new_vals_list = self._prepare_create_values(vals_list)
  File "/usr/local/lib/python3.10/dist-packages/odoo/models.py", line 4699, in _prepare_create_values
    vals = self._add_missing_default_values(vals)
  File "/usr/local/lib/python3.10/dist-packages/odoo/models.py", line 1795, in _add_missing_default_values
    defaults = self.default_get(missing_defaults)
  File "/usr/local/lib/python3.10/dist-packages/odoo/addons/base/models/res_config.py", line 464, in default_get
    classified = self._get_classified_fields(fields)
  File "/usr/local/lib/python3.10/dist-packages/odoo/addons/base/models/res_config.py", line 443, in _get_classified_fields
    raise Exception("Field %s must have type 'boolean', 'integer', 'float', 'char', 'selection', 'many2one' or 'datetime'" % field)
Exception: Field res.config.settings.product_tag_ids must have type 'boolean', 'integer', 'float', 'char', 'selection', 'many2one' or 'datetime'
`

**Comment by CybroOdoo** [comment]
Hi @nth-zik ,
We will check the issue and get back to you.
