### ISSUE TITLE
[Odoo 10.0] website_event_attachements clicking on the attachment at the front end brings up error.

### ISSUE THREAD

**Issue by arafatx** [CybroOdoo/CybroAddons#32]
The plugin can be set correctly in the backend and the attachment is shown properly at the front end. Only one problem, when clicking on the attachment (with the intention to download/view), a blank page with the error message below appear:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

And this is the odoo log file (i filtered the log result only when i click on the attachment):

2017-09-22 12:59:30,415 3675 INFO emaxidb werkzeug: 172.104.189.112 - - [22/Sep/2017 12:59:30] "GET /attachment/download?attachment_id=1274 HTTP/1.1" 500 -
2017-09-22 12:59:30,429 3675 ERROR emaxidb werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/service/server.py", line 249, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1308, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1282, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1481, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/addons/website/models/ir_http.py", line 218, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/opt/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/addons/website/models/ir_http.py", line 270, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper

**Comment by CybroOdoo** [comment]
Please check with the latest version
