### ISSUE TITLE
Module installation error

### ISSUE THREAD

**Issue by ndkazu** [CybroOdoo/CybroAddons#39]
Hello,

I'm trying to install the module on Odoo Community 10 in Windows 7, but every time I get the following error:

[Element '<fierld name ="Progress">' cannot be located in parent view
Error context:
View 'project task timer'
....]

and the module won't be installed. 
any hint on how to solve this?

Ndong

**Comment by zeroheure** [comment]
you should provide more infos : what module, version and full error message

**Comment by ndkazu** [comment]
Hello,
First of all, Thank you for your answer.
I believe the app version is '10.0.2.0.0' (seen in the changelog.rst file, located in the "doc" folder).
The full detailed error message is as follows:

```
Traceback (most recent call last):
  File "C:\ptc\Odoo 10.0\server\odoo\http.py", line 640, in _handle_exception
  File "C:\ptc\Odoo 10.0\server\odoo\http.py", line 677, in dispatch
  File "C:\ptc\Odoo 10.0\server\odoo\http.py", line 333, in _call_function
  File "C:\ptc\Odoo 10.0\server\odoo\service\model.py", line 101, in wrapper
  File "C:\ptc\Odoo 10.0\server\odoo\http.py", line 326, in checked_call
  File "C:\ptc\Odoo 10.0\server\odoo\http.py", line 935, in __call__
  File "C:\ptc\Odoo 10.0\server\odoo\http.py", line 506, in response_wrap
  File "C:\ptc\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 889, in call_button
  File "C:\ptc\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 877, in _call_kw
  File "C:\ptc\Odoo 10.0\server\odoo\api.py", line 689, in call_kw
  File "C:\ptc\Odoo 10.0\server\odoo\api.py", line 680, in call_kw_multi
  File "C:\ptc\Odoo 10.0\server\odoo\addons\base\module\module.py", line 410, in button_immediate_install
  File "C:\ptc\Odoo 10.0\server\odoo\addons\base\module\module.py", line 484, in _button_immediate_function
  File "C:\ptc\Odoo 10.0\server\odoo\modules\registry.py", line 82, in new
  File "C:\ptc\Odoo 10.0\server\odoo\modules\loading.py", line 339, in load_modules
  File "C:\ptc\Odoo 10.0\server\odoo\modules\loading.py", line 237, in load_marked_modules
  File "C:\ptc\Odoo 10.0\server\odoo\modules\loading.py", line 156, in load_module_graph
  File "C:\ptc\Odoo 10.0\server\odoo\modules\loading.py", line 95, in _load_data
  File "C:\ptc\Odoo 10.0\server\odoo\tools\convert.py", line 845, in convert_file
  File "C:\ptc\Odoo 10.0\server\odoo\tools\convert.py", line 915, in convert_xml_import
  File "C:\ptc\Odoo 10.0\server\odoo\tools\convert.py", line 796, in parse
  File "C:\ptc\Odoo 10.0\server\odoo\tools\convert.py", line 799, in parse
  File "C:\ptc\Odoo 10.0\server\odoo\tools\convert.py", line 707, in _tag_record
  File "C:\ptc\Odoo 10.0\server\odoo\addons\base\ir\ir_model.py", line 1229, in _update
  File "C:\ptc\Odoo 10.0\server\odoo\addons\base\ir\ir_ui_view.py", line 362, in create
  File "C:\ptc\Odoo 10.0\server\odoo\models.py", line 3834, in create
  File "C:\ptc\Odoo 10.0\server\odoo\fields.py", line 1041, in determine_inverse
  File "C:\ptc\Odoo 10.0\server\odoo\addons\base\ir\ir_ui_view.py", line 220, in _inverse_arch
  File "C:\ptc\Odoo 10.0\server\odoo\addons\base\ir\ir_ui_view.py", line 380, in write
  File "C:\ptc\Odoo 10.0\server\odoo\models.py", line 3560, in write
  File "C:\ptc\Odoo 10.0\server\odoo\models.py", line 3711, in _write
  File "C:\ptc\Odoo 10.0\server\odoo\models.py", line 1083, in _validate_fields
ParseError: "Error while validating constraint

Element '<field name="progress">' cannot be located in parent view

Error context:
View `project task timer`
[view_id: 1337, xml_id: n/a, model: project.task, parent_id: 361]
None" while parsing file:///c:/ptc/addons/project_task_timer/views/project_task_timer_view.xml:4, near
<record id="project_task_timer_inherit_view" model="ir.ui.view">
            <field name="name">project task timer</field>
            <field name="model">project.task</field>
            <field name="inherit_id" ref="project.view_task_form2"/>
            <field name="arch" type="xml">
                <data><div name="button_box" position="inside">
                    <button name="toggle_start" type="object" class="oe_stat_button" icon="fa-clock-o">
                        <field name="task_timer" widget="boolean_button" options="{&quot;terminology&quot;: {                                     &quot;string_true&quot;: &quot;Started&quot;,                                     &quot;hover_true&quot;: &quot;Pause&quot;,                                     &quot;string_false&quot;: &quot;Timer&quot;,                                     &quot;hover_false&quot;: &quot;Start&quot;                                 }}"/>
                    </button>
                </div>
                <field name="progress" position="after">
                    <field name="is_user_working" invisible="1"/>
                    <label for="duration"/>
                    <div>
                        <button style="pointer-events: none;" class="oe_inline label label-default">
                            <field name="duration" widget="time_counter"/>
                        </button>
                    </div>
                </field>
            </data></field>
        </record>
```

Ndong

**Comment by ndkazu** [comment]
Sorry i forgot the module name again: **"Project Task Timer"**

**Comment by zeroheure** [comment]
I'm not from Cybro. I was browsing here while I've read your message.
The error message is very clear : a view from "Project Task Timer" try to inherit another one. It try to position some field, label and button after the field named "progress" from the view it try to inherit (the parent view). But it can't find the field named "progress". This an XPath issue. Odoo use XPath to locate elements in XML. Have a look in the parent view and try to change the XPath element (XPath is very simple and easy to learn).
You have fiew element to look for in the parent view : its id in database and module name (project).

Edit : Cybro has fixed the error yesterday. See https://github.com/CybroOdoo/CybroAddons/commit/d52fdea0743300ac01befcae43267dc67b0622d4  Just download the new version.

**Comment by CybroOdoo** [comment]
Fixed the issue. 
Enjoy guys.
