### ISSUE TITLE
Sales Discount App error - Odoo 9

### ISSUE THREAD

**Issue by NeerajaRagesh** [CybroOdoo/CybroAddons#52]
I installed sales discount on total in sales order. While creating invoice am getting the below error
Odoo Server Error
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in call
return self.method(*args, **kw)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 878, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
return call_kw_multi(method, model, args, kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
result = method(recs, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5469, in onchange
record._onchange_eval(name, field_onchange[name], result)
File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5367, in _onchange_eval
method_res = method(self)
File "/usr/lib/python2.7/dist-packages/odoo/addons/account/models/account_invoice.py", line 456, in _onchange_invoice_line_ids
taxes_grouped = self.get_taxes_values()
File "/usr/lib/python2.7/dist-packages/odoo/addons/account/models/account_invoice.py", line 635, in get_taxes_values
val = self._prepare_tax_line_vals(line, tax)
File "/usr/lib/python2.7/dist-packages/odoo/addons/account/models/account_invoice.py", line 612, in _prepare_tax_line_vals
'base': tax['base'],
KeyError: 'base'

please give any solution

**Comment by CybroOdoo** [comment]
Please check the module with a new copy of Odoo 9.
We couldn't regenerate this error here
