### ISSUE TITLE
Installation error on a fresh db, looking up for and undefined id. While trying to install ohrms_core

### ISSUE THREAD

**Issue by hilarak** [CybroOdoo/CybroAddons#68]
```
Traceback (most recent call last):
  File "/home/dell/hilar/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dell/hilar/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/dell/hilar/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dell/hilar/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dell/hilar/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dell/hilar/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/dell/hilar/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/dell/hilar/odoo/addons/web/controllers/main.py", line 895, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/dell/hilar/odoo/addons/web/controllers/main.py", line 883, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/dell/hilar/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/dell/hilar/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/dell/hilar/odoo/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/dell/hilar/odoo/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/dell/hilar/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/dell/hilar/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/home/dell/hilar/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/dell/hilar/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/dell/hilar/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/dell/hilar/odoo/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/dell/hilar/odoo/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/dell/hilar/odoo/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/dell/hilar/odoo/odoo/tools/convert.py", line 546, in _tag_menuitem
    group_id = self.id_get(group)
  File "/home/dell/hilar/odoo/odoo/tools/convert.py", line 782, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/dell/hilar/odoo/odoo/tools/convert.py", line 788, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/dell/hilar/odoo/odoo/addons/base/ir/ir_model.py", line 1076, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-8>", line 2, in xmlid_lookup
  File "/home/dell/hilar/odoo/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/dell/hilar/odoo/odoo/addons/base/ir/ir_model.py", line 1065, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: hr_appraisal.group_appraisal_manager" while parsing /home/dell/hilar/odoo/ohrms_core-10.0.1.0.0/oh_appraisal/views/hr_appraisal_form_view.xml:178, near
<menuitem name="Appraisal" id="menu_hr_appraisal_root" parent="hr.menu_hr_root" groups="hr_appraisal.group_appraisal_manager,hr_appraisal.group_appraisal_employee"/>
```

**Comment by CybroOdoo** [comment]
Hi Hilar,
We updated the module. Get a new copy
