### ISSUE TITLE
IOError: File not found: oh_employee_creation_from_user/employee_creation_from_user_view.xml

### ISSUE THREAD

**Issue by hilarak** [CybroOdoo/CybroAddons#69]
```
Traceback (most recent call last):
  File "/home/dell/hilar/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dell/hilar/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/dell/hilar/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dell/hilar/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dell/hilar/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dell/hilar/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/dell/hilar/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/dell/hilar/odoo/addons/web/controllers/main.py", line 895, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/dell/hilar/odoo/addons/web/controllers/main.py", line 883, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/dell/hilar/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/dell/hilar/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/dell/hilar/odoo/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/dell/hilar/odoo/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/dell/hilar/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/dell/hilar/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/home/dell/hilar/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/dell/hilar/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/dell/hilar/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/dell/hilar/odoo/odoo/tools/convert.py", line 834, in convert_file
    fp = file_open(pathname)
  File "/home/dell/hilar/odoo/odoo/tools/misc.py", line 195, in file_open
    return _fileopen(name, mode=mode, basedir=rtp, pathinfo=pathinfo, basename=basename)
  File "/home/dell/hilar/odoo/odoo/tools/misc.py", line 251, in _fileopen
    raise IOError('File not found: %s' % basename)
IOError: File not found: oh_employee_creation_from_user/employee_creation_from_user_view.xml
```

**Comment by CybroOdoo** [comment]
Fixed
