### ISSUE TITLE
Odoo 10 Sale discount invoice error

### ISSUE THREAD

**Issue by Albertuch0** [CybroOdoo/CybroAddons#7]
Hello, I've install your discount module in odoo 10, ant it works good making sale orders. But doing invoices I obtain this error:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5469, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5367, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account/models/account_invoice.py", line 456, in _onchange_invoice_line_ids
    taxes_grouped = self.get_taxes_values()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account/models/account_invoice.py", line 635, in get_taxes_values
    val = self._prepare_tax_line_vals(line, tax)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account/models/account_invoice.py", line 612, in _prepare_tax_line_vals
    'base': tax['base'],
KeyError: 'base'

Any ideas to fix this?

**Comment by CybroOdoo** [comment]
Hello,

Can you please explain the use case because we are not getting the error
here.

With Regards,

Cybro Odoo Team

**Comment by Albertuch0** [comment]
Hello Cybro, I've been doing some proofs and it seems a compatibility problem with Sales order type addon. After I unistall that, your module works good.

Sorry for the false alarm.

Only one question. I've been trying to apply discounts to multiple invoices via mass editing, but after that  I  still must cancel and edit invoices one by one to reflect amount changes. Do you know how to automatically apply amount changes after applying discounts via mass editing?

Thank you

**Comment by CybroOdoo** [comment]
We haven't checked that part yet. Let you know when we check it

With Regards,
Cybro Odoo Team

**Comment by rdcprojects** [comment]
I am still getting this error without any third party addons.
