### ISSUE TITLE
[10.0] product_return_pos error

### ISSUE THREAD

**Issue by rodrig92** [CybroOdoo/CybroAddons#76]
When I try to load POS:
point_of_sale.assets.js:124 Cannot set property 'return_ref' of undefined TypeError: Cannot set property 'return_ref' of undefined
    at child.initialize (http://192.168.250.141:9069/web/content/36898-cea1622/point_of_sale.assets.js:559:301)
    at child.Backbone.Model (http://192.168.250.141:9069/web/content/36886-001f52d/web.assets_backend.js:1223:1299)
    at child [as constructor] (http://192.168.250.141:9069/web/content/36886-001f52d/web.assets_backend.js:1265:455)
    at child [as constructor] (http://192.168.250.141:9069/web/content/36886-001f52d/web.assets_backend.js:1265:455)
    at child [as constructor] (http://192.168.250.141:9069/web/content/36886-001f52d/web.assets_backend.js:1265:455)
    at child [as constructor] (http://192.168.250.141:9069/web/content/36886-001f52d/web.assets_backend.js:1265:455)
    at child [as constructor] (http://192.168.250.141:9069/web/content/36886-001f52d/web.assets_backend.js:1265:455)
    at new child (http://192.168.250.141:9069/web/content/36886-001f52d/web.assets_backend.js:1265:455)
    at child.load_orders (http://192.168.250.141:9069/web/content/36898-cea1622/point_of_sale.assets.js:126:1272)
    at child.after_load_server_data (http://192.168.250.141:9069/web/content/36898-cea1622/point_of_sale.assets.js:113:250)

You can solve it with two lines:
In pos_return.js line 462:
if (typeof(order) != 'undefined'){
   order.return_ref = ' '
}
and in the pos_return.py file, line 53:
if 'return_ref' in ui_order.keys() and ui_order['return_ref']:
.......

I hope I have been helpful to you, and thank you very much for the module.

**Comment by CybroOdoo** [comment]
Hi rodrig92,
We fixed this issue, thanks for your support
