### ISSUE TITLE
Unable to Confirm Sales Order After Installing Quality Assurance on Odoo 11 CE.

### ISSUE THREAD

**Issue by wshamasneh** [CybroOdoo/CybroAddons#92]
Dear Sir:

First of all, let me thank you for the great addons that add real value to Odoo.

On of your great addons is the Quality Assurance which is fact is not available at Odoo CE, but after installing the Quality Assurance on Odoo 11 CE with Demo Data and before installing any other Addon, I have tried to perform a full cycle for the Sales Processes and after confirming the Sales Quotation using the button Confirm Sale, the following error raised up:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale_timesheet\models\sale_order.py", line 62, in action_confirm
    result = super(SaleOrder, self).action_confirm()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\event_sale\models\sale_order.py", line 11, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale\models\sale.py", line 554, in action_confirm
    self._action_confirm()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale_stock\models\sale_order.py", line 40, in _action_confirm
    order.order_line._action_launch_procurement_rule()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\procurement_jit\sale.py", line 18, in _action_launch_procurement_rule
    reassign.action_assign()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\stock\models\stock_picking.py", line 585, in action_assign
    self.filtered(lambda picking: picking.state == 'draft').action_confirm()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\quality_assurance\models\stock.py", line 64, in action_confirm
    res = super(StockPicking, self)._action_confirm()
AttributeError: 'super' object has no attribute '_action_confirm'

**Comment by CybroOdoo** [comment]
Thanks for informing
Bug Fixed

**Comment by wshamasneh** [comment]
Thank you so much. I will test the case soon.

**Comment by wshamasneh** [comment]
Thank you. Tested and now the Sales Orders work properly.
